django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('todo/', include('todo.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='todo/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.ListListView.as_view(), name="index"),
    path('index', views.ListListView.as_view()),
    path("login", views.login_request, name="login"),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("list/<int:list_id>/", views.ItemListView.as_view(), name="list"),
    #path("deneme", views.denemelere)
    # CRUD patterns for ToDoLists
    path("list/add/", views.ListCreate.as_view(), name="list-add"),
    # CRUD patterns for ToDoItems
    path(
        "list/<int:list_id>/item/add/",
        views.ItemCreate.as_view(),
        name="item-add",
    ),
    path(
         "list/<int:list_id>/item/<int:pk>/",
        views.ItemUpdate.as_view(),
        name="item-update",
    ),
    path(
        "list/<int:pk>/delete/", views.ListDelete.as_view(), name="list-delete"
    ),
    path(
        "list/<int:list_id>/item/<int:pk>/delete/",
        views.ItemDelete.as_view(),
        name="item-delete",
    ),
]

todo/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse


# Create your models here.
class Todo(models.Model):
    baslik = models.CharField(max_length=120)
    aciklama = models.TextField()
    tamamlandi = models.BooleanField(default=False)

    def get_absolute_url(self):
        """Returns the URL to access a particular instance of the model."""
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.baslik


def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)


class ToDoList(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        return reverse("todo:list", args=[self.id])

    def __str__(self):
        return self.title


class ToDoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("todo:item-update",
                       args=[str(self.todo_list.id),
                             str(self.id)])

    def __str__(self):
        return f"{self.title}: {self.due_date} Tarihinde sona eriyor"

    class Meta:
        ordering = ["due_date"]

todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

todo/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from .models import Todo, ToDoList, ToDoItem
from django.template import loader
from django.views.generic import (ListView, CreateView, UpdateView, DeleteView)
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    #model = Todo
    #context_object_name = 'todo_listesi'
    queryset = Todo.objects.all()
    template_name = 'todo/index.html'
    context = {'todo_listesi': queryset}
    loader.get_template('todo/yapilacaklar.html')
    return render(request, template_name, context)


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Kayıt başarılı.")
            return redirect('todo:index')
        else:
            messages.error(request, "Kayıt başarısız. Geçersiz bilgi.")
            return redirect('todo:register')
    else:
        form = NewUserForm()
        return render(request=request,
                      template_name="todo/register.html",
                      context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"{username} olarak giriş yaptınız.")
                return redirect('todo:index')
            else:
                messages.error(request, 'Kullanıcı adı veya şifre hatalı.')
                return redirect('todo:index')
        else:
            messages.error(request, 'Kullanıcı adı veya şifre hatalı.')
            return redirect('todo:login')
    else:
        form = AuthenticationForm()
        return render(request=request,
                      template_name="todo/login.html",
                      context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Başarıyla çıkış yaptınız.")
    return redirect("todo:index")


def denemelere(request):
    return render(request, "todo/deneme.html")


class ListListView(ListView):
    model = ToDoList
    template_name = "todo/index.html"


class ItemListView(ListView):
    model = ToDoItem
    template_name = "todo/todo_list.html"

    def get_queryset(self):
        return ToDoItem.objects.filter(todo_list_id=self.kwargs["list_id"])

    def get_context_data(self):
        context = super().get_context_data()
        context["todo_list"] = ToDoList.objects.get(id=self.kwargs["list_id"])
        return context


class ListCreate(CreateView):
    model = ToDoList
    fields = ["title"]

    def get_context_data(self):
        context = super(ListCreate, self).get_context_data()
        context["title"] = "Yeni bir liste oluştur"
        return context


class ItemCreate(CreateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_initial(self):
        initial_data = super(ItemCreate, self).get_initial()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        initial_data["todo_list"] = todo_list
        return initial_data

    def get_context_data(self):
        context = super(ItemCreate, self).get_context_data()
        todo_list = ToDoList.objects.get(id=self.kwargs["list_id"])
        context["todo_list"] = todo_list
        context["title"] = "Yeni Bir Öğe Oluştur"
        return context

    def get_success_url(self):
        return reverse("todo:list", args=[self.object.todo_list_id])


class ItemUpdate(UpdateView):
    model = ToDoItem
    fields = [
        "todo_list",
        "title",
        "description",
        "due_date",
    ]

    def get_context_data(self):
        context = super(ItemUpdate, self).get_context_data()
        context["todo_list"] = self.object.todo_list
        context["title"] = "Öğeyi Düzenle"
        return context

    def get_success_url(self):
        return reverse("todo:list", args=[self.object.todo_list_id])


class ListDelete(DeleteView):
    model = ToDoList
    # You have to use reverse_lazy() instead of reverse(),
    # as the urls are not loaded when the file is imported.
    success_url = reverse_lazy("todo:index")


class ItemDelete(DeleteView):
    model = ToDoItem

    def get_success_url(self):
        return reverse_lazy("todo:list", args=[self.kwargs["list_id"]])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_list"] = self.object.todo_list
        return context

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Gerekli meta etiketleri -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <title>{% block title %} {% endblock %} | Yapılacaklar Listem</title>
  </head>
 <body>
     <!---Mesajlar--->
{% for message in messages %}
     <div class="container-fluid p-0">
         <div class="alert {{ message.tags }} alert-dismissible">
             <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
             {{ message }}
        </div>
     </div>
{% endfor %}

    {% block content %}

    {% endblock %} 

    {% block yapcaklar %}

    {% endblock %} 
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

todo/templates/todo/deneme.html
{% extends "base.html" %}
{% block title %} Anasayfa {% endblock %}

{% block content %}
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16">
  <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
</svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Anasayfa</a></li>
        <!--
        <li><a href="#" class="nav-link px-2 link-dark">Features</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
        -->
      </ul>

      <div class="col-md-3 text-end">
        <button type="button" class="btn btn-outline-primary me-2">Giriş Yap</button>
        <button type="button" class="btn btn-primary">Kaydol</button>
      </div>
    </header>
  </div>
{% endblock %} 

todo/templates/todo/index.html
{% extends "base.html" %}
{% block title %} Anasayfa {% endblock %}
<body>
    {% block content %}

  <!-- Header -->
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Anasayfa</a></li>
        <!--
        <li><a href="#" class="nav-link px-2 link-dark">Features</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
        -->
      </ul>

      <div class="col-md-3 text-end">
        {% if user.is_authenticated %}
        <a class="nav-link px-2 link-secondary">Hoşgeldiniz, {{user.username}}</a>
        <a type="button" class="btn btn-outline-primary me-2" href="{% url 'todo:logout' %}">Çıkış Yap</a>
        
        {% else %}
        <a type="button" class="btn btn-outline-primary me-2" href="{% url 'todo:login' %}" >Giriş Yap</a>
        <a type="button" class="btn btn-primary" href="{% url 'todo:register' %}">Kaydol</a>

        {% endif %}
      </div>
    </header>
  </div>

  <!-- / Header End -->
    <!--Navbar--><!--
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Yapılacaklar.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
    
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:logout' %}">Çıkış Yap</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Hoşgeldiniz, {{user.username}}</a>
                </li>


              
                {% else %}
    
                <li class="nav-item">
                    <a style="float:right" class="nav-link" href="{% url 'todo:login' %}">Giriş Yap</a>
                    <a style="float:right" class="nav-link" href="{% url 'todo:register' %}">Kayıt Ol</a>
                </li>
    
                {% endif %}
            </ul>
        </div>
    </nav>
    
-->

  
{% if user.is_authenticated %}   
    {% if object_list %}
    <h3>Yapılacaklar Listeleri</h3>
    {% endif %}
    <ul>
        {% for todolist in object_list %}
        <li>
            <div
                role="button"
                onclick="location.href='{% url "todo:list" todolist.id %}'">
                {{ todolist.title }}
            </div>
        </li>
        {% empty %}
        <h4>You have no lists!</h4>
        {% endfor %}
    </ul>
    <p>
    <input
        value="Yeni bir liste oluştur"
        type="button"
        onclick="location.href='{% url "todo:list-add" %}'"/>
</p>
{% else %}
    <div>
        <br/>
        <h1>Yapılacaklar Listesi Oluşturun.</h1>
        <br/>
        <h2>Basit ve Hızlı.</h2>
        <br/>
        <p>Yalnızca hızlı bir üyelikle, sınırsız bir şekilde kendi yapılacaklar listenizi oluşturmaya başlayabilirsiniz.</p>
        <p>Giriş yapmanız durumunda, listeleriniz tam da burada gözükmeye başlayacak.</p>
        
{% endif %}
        

    {% endblock %}

</body>

todo/templates/todo/login.html
{% extends "base.html" %}
{% block title %} Giriş Yap {% endblock %}
{% block content %}      

{% load crispy_forms_tags %}



<!--Login--> 
<div class="container py-5">
  <h1>Giriş Yap</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Hesabınız yok mu? <a href="{% url 'todo:register' %}">Kayıt olun</a>.</p>
</div>

{% endblock %}

todo/templates/todo/register.html
{% extends "base.html" %}
{% block title %} Üye Ol {% endblock %}
{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Kayıt ol</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Kayıt Ol</button>
	</form>
	<p class="text-center">Eğer bir hesabınız varsa, bunun yerine <a href="{% url 'todo:login' %}">giriş yapmayı</a> deneyin.</p>
</div>

{% endblock %}

todo/templates/todo/todo_list.html
{% extends "base.html" %}
{% block title %} {{ todo_list.title }} {% endblock %}
{% block content %}
<body>
{% if user.is_authenticated %}
    <div>
        <div>
            <div>
                <h3>Listeyi düzenle:</h3>
                <h5>{{ todo_list.title | upper }}</h5>
            </div>
            <ul>
                {% for todo in object_list %}
                <li>
                    <div>
                        <div
                            role="button"
                            onclick="location.href='{% url "todo:item-update" todo_list.id todo.id %}'">
                            {{ todo.title }}
                            (Due {{ todo.due_date | date:"l, F j" }})
                        </div>
                    </div>
                </li>
                {% empty %}
                <p>Bu listede herhangi bir öğe yok.</p>
                {% endfor %}
            </ul>
            <p>
                <input
                    value="Yeni bir öğe ekle"
                    type="button"
                    onclick="location.href='{% url "todo:item-add" todo_list.id %}'" />
                <input
                    value="Bu listeyi sil"
                    type="button"
                    onclick="location.href=
                    '{% url "todo:list-delete" todo_list.id %}'" />
                <input
                    value="Anasayfa"
                    type="button"
                    onclick="location.href='{% url "todo:index" %}';">
            </p>
            </p>
        </div>
    </div>

{% else %}
    <p>NO.</p>
{% endif %}
</body>
{% endblock %}

todo/templates/todo/todoitem_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h3>Öğeyi Sil</h3>

<p><i>{{ todo_list.title }}</i> adlı listeden <b>{{ object.title }}</b> öğesini silmek istediğinize emin misiniz? ?</p>

<form method="POST">
    {% csrf_token %}
    <input
        value="Evet, silmek istiyorum."
        type="submit">
    <input
        value="Vazgeç"
        type="button"
        onclick="location.href='{% url "todo:list" todo_list.id %}';">
</form>

{% endblock %}

todo/templates/todo/todoitem_form.html
{% extends "base.html" %}
{% block title %} {{ todoitem.title }} {% endblock %}
{% block content %}

<h3>{{ title }}</h3>
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input
        value="Gönder"
        type="submit">
    <input
        value="Vazgeç"
        type="button"
        onclick="location.href='{% url "todo:list" todo_list.id %}'">
    {% if object %}
        <input
            value="Bu öğeyi sil"
            type="button"
            onclick="location.href=
            '{% url "todo:item-delete" todo_list.id object.id %}'">
    {% endif %}

</form>

{% endblock %}

todo/templates/todo/todolist_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<!--todolist_confirm_delete.html-->

<h3>Listeyi sil</h3>

<p><i>{{ object.title }}</i> adlı listyi silmek istediğiniden emin misiniz?</p>

<form method="POST">
    {% csrf_token %}
    <input
        value="Evet, silmek istiyorum."
        type="submit">
</form>
<input
    value="Vazgeç"
    type="button"
    onclick="location.href='{% url "todo:index" %}';">

{% endblock %}

todo/templates/todo/todolist_form.html
{% extends "base.html" %}

{% block content %}

<h3>{{ title }}</h3>
<div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input
                value="Kaydet"
                type="submit">
            <input
                value="Vazgeç"
                type="button"
                onclick="location.href='{% url "todo:index" %}';">
        </form>
    </div>
</div>

{% endblock %}

todo/templates/todo/yapilacaklar.html
{% extends "todo/index.html" %}

{% block yapcaklar %}      

<h1>Yapilacaklar</h1>
  {% if todo_listesi %}
  <ul>
    {% for yapilacak in todo_listesi %}
      <li>
        {{ yapilacak.baslik }}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Yapılacaklar listesi boş.</p>
  {% endif %}

{% endblock %}